[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "qvc"
version = "0.1.0"
description = "Quasar variability cosmology workflows"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astropy==7.1.0",
    "corner==2.2.3",
    "dynesty==2.1.5",
    "dustmaps",
    "h5py==3.14.0",
    "jax==0.6.2",
    "jaxlib==0.6.2",
    "jaxopt",
    "equinox==0.12.2",
    #"jaxqsofit @ git+https://github.com/burke86/jaxqsofit.git",
    #"EzTaoX==0.2.0",
    "matplotlib==3.10.0",
    "numpy==2.3.1",
    "numpyro==0.19.0",
    "pandas==2.3.1",
    "pyarrow==19.0.0",
    "rich>=13.0",
    "scipy==1.16.0",
    "speclite",
    "statsmodels",
    "tinygp==0.3.0",
    "tqdm==4.67.1",
    "gdown==5.2.1",
    "colorama==0.4.6",
    "statsmodels==0.14.6",
    "jaxns>=2.6.9"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["qvc*"]

[tool.setuptools.package-data]
"qvc.hubble" = ["style.mplstyle"]
"qvc.hubble._vendor.qsogen" = ["*.dat", "*.sed", "*.sph", "LICENSE.md"]
"qvc.hubble._vendor.jaxsedfit_filters" = ["*.dat", "*.md", "*.txt"]
"qvc.light_curve" = ["style.mplstyle"]
