"""Centralized parameter-cut thresholds for the QVC Hubble pipeline."""

APPARENT_MAG_2500_MIN = None #16.0
APPARENT_MAG_2500_MAX = None #24.0

LOG_TAU_UV_RF_MIN = 1.5
LOG_TAU_UV_RF_MAX = 4.0
WRMS_MAX = 1.2
T_RF_LENGTH_MIN = 1700.0
F_HOST_2500_MAX = None
FRAC_HOST_PSF_2500_MAX = None
ALPHA_LAMBDA_MIN = None
ALPHA_LAMBDA_MAX = None
VARIABILITY_CHI_SQ_RED_G_MIN = 20.0
LOG_SIGMA_UV_MIN = -1.5
LOG_SIGMA_UV_MAX = 0.2
REDDENING_EBV_MAX = None

LOG_AMP_DELTA_BLR_UPPER = 0
LOG_AMP_DELTA_BLR_UPPER_BY_BAND = {
    "u": LOG_AMP_DELTA_BLR_UPPER,
    "g": LOG_AMP_DELTA_BLR_UPPER,
    "r": LOG_AMP_DELTA_BLR_UPPER,
    "i": LOG_AMP_DELTA_BLR_UPPER,
}
LOG_AMP_DELTA_BC_UPPER = -0.2
LOG_F_BC_3000_MAX = -2.0
LOG_F_FE_UV_3000_MAX = -2.0
REL_APPARENT_MAG_2500_ERR_MAX = 0.003
APPARENT_MAG_2500_ERR_MIN = 0.0
FRAC_ERR_LOG_L2500_MAX = 500

ALPHA_LAMBDA_REQUIRED_COLUMNS = ("alpha_lambda", "alpha_lambda_err")
EXCLUDED_SDSS_NAMES = (
    "221120.38+010905.6",
    "024555.35+005332.6",
    "015802.36+002917.3",
)
AGN_SCALAR_PARAMETER_CUTS = (
    ("log_tau_uv_rf", LOG_TAU_UV_RF_MIN, LOG_TAU_UV_RF_MAX),
    ("wrms", None, WRMS_MAX),
    ("t_rf_length", T_RF_LENGTH_MIN, None),
    ("f_host_2500", None, F_HOST_2500_MAX),
    ("frac_host_psf_2500", None, FRAC_HOST_PSF_2500_MAX),
    ("alpha_lambda", ALPHA_LAMBDA_MIN, ALPHA_LAMBDA_MAX),
    ("variability_chi_sq_red_g", VARIABILITY_CHI_SQ_RED_G_MIN, None),
    ("log_sigma_uv", LOG_SIGMA_UV_MIN, LOG_SIGMA_UV_MAX),
)
